# Generated by Django 5.1.3 on 2024-11-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_venda_produtos_itensdopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
